apiVersion: v1
kind: Service
metadata:
  name: deployment-demo-green
spec:
  type: LoadBalancer
  selector:
    app: deployment-demo-green
    deployment: green
    version: 1.0.1
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP